[workspace]
resolver = "3"
members = [
    # "tonlibjson-sys",
    "tl_parser",
    "adnl-tcp",
    "ton-client-util",
    # "tonlibjson-client",
    "ton-liteserver-client",
    # "ton-contract",
    # "ton-grpc",
    # "tvm-grpc",
]

[workspace.dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
async-trait = "0.1.88"
tower = { version = "0.5.2", features = ["full"] }
tokio = { version = "1.45", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
tokio-stream = { version = "0.1", features = ["sync"] }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-futures = { version = "0.2", features = ["std", "std-future", "futures-03"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["serde_derive"] }
base64 = "0.22"
hex = "0.4"
tracing-test = "0.2"
async-stream = "0.3"
toner = "0.5"
num-bigint = "0.4"
tonic = { version = "0.11", features = ["gzip"] }
tonic-reflection = "0.11"
tonic-health = "0.11"
tonic-build = "0.11"
prost = "0.12"
quick_cache = "0.6"
url = { version = "2.5", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
humantime = "2.1"
uuid = { version = "1.14", features = ["v4", "fast-rng", "serde"] }
dashmap = "6.1"
pin-project = "1.1"
rand = "0.9"
bytes = "1.9"
thiserror = "1.0"
itertools = "0.14"
bitvec = "1.0"
metrics = "0.24"
reqwest = { version = "0.12", features = ["rustls-tls", "hickory-dns"], default-features = false }
hickory-resolver = { version = "0.24", features = ["tokio-runtime"] }
tokio-retry = "0.3"
derive_more = { version = "2.0", features = ["debug"] }
quote = "1.0"
syn = "2.0"
prettyplease = "0.2"
convert_case = "0.8"
nom = "8.0.0"
crc32fast = "1.4.2"
sha2 = "0.10"
aes = "0.8"
ctr = "0.9"
ed25519-dalek = { version = "2.1", features = ["rand_core", "hazmat"] }
